import functools

l=[1,2,3,4,5]
sum=functools.reduce(lambda acc,num:acc+num, l)
print("Sum= ",sum)


lst = ["Python","Perl","Linux","OS"]
con= functools.reduce(lambda acc,num:acc+" "+num+" ", lst)
print(con)

#Write a function to find a string generated by concatenation of 2nd and 3rd character of a string

fun= functools.reduce(lambda acc,s:acc+s[1:3], lst,"") 
print(fun)